# TODO generate documention from schema?
type: object
required: [users, servers]
properties:
  users:
    type: object
    default: {}
    additionalProperties:
      type: object
      properties:
        key: { type: string }
        uid: { type: integer }
        group: { type: string }
        enabled: { type: boolean }
        additional_groups:
          type: array
          items:
            type: string
  servers:
    type: object
    additionalProperties:
      type: object
      properties:
        name: { type: string }
        hostname: { type: string }
        port: { type: integer }
        ssh_user: { type: string }
        users:
          type: array
          items:
            type: string
        like: { type: string }
        keepOtherKeys: { type: boolean }
      additionalProperties: false
additionalProperties: false
# vim: sw=2 ts=2 et
